### ISSUE TITLE
Possible collaboration?

### ISSUE THREAD

**Issue by cnlohr** [fmaurer/FreePIE-VR-Controls#1]
Would you be interested in working together on this sort of platform?  Specifically, I was wondering if I were to get many sensors working in parallel with an ESP32 if it is something you could port on the backend to the different interfaces on your side and potentially port your interface to my frontend in libsurvive - admittedly it's not quite 100% there yet.

**Comment by fmaurer** [comment]
What an honor, I watched all your VODs!

I'm not exactly sure how I fit in but I'm more than happy to help how I can. I'm 95% sure whatever you come up with, we can make it work with FreePIE/Python. I watched your esp32 mouse+keyboard vod;  I'm currently passing quaternions over a joystick axis HID report since I can combine it with buttons. There are some limitations in using FreePIE to emulate the Vive wands, but it's at least convenient to test ideas with.

**Comment by cnlohr** [comment]
Oh! I thought you were somehow utilizing the lighthouse data!  Regardless, even if that's not the case, you clearly have figured out ways of feeding data back into the valve subsystems.  One of the things a little later on is where we will be using ESP32s to read current location.   Initially it will only work with our subsystem, but it will certainly be super cool to take that and feed it into the larger vive ecosystem.

**Comment by cnlohr** [comment]
Additionally, you have a much firmer grasp on actual controllerifying things than I do.   Maybe we should check back in a few weeks?

**Comment by fmaurer** [comment]
Sounds good, let's stay in touch. I'll be following your youtubes

**Comment by cnlohr** [comment]
Cool!
